service: serverless-aws-terraform-intro

frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:*
      # NOTE: App will not work when DynamoDB table ARN will be different
      # than the one specified below.
      Resource: arn:aws:dynamodb:eu-central-1:705130529207:table/ChatMessages

functions:
  addChatMessage:
    handler: src/addChatMessage.handler
    events:
      - httpApi:
          path: /
          method: post
  fetchChatMessage:
    handler: src/fetchChatMessage.handler
    events:
      - httpApi:
          path: /{id}
          method: get
  fetchChatMessages:
    handler: src/fetchChatMessages.handler
    events:
      - httpApi:
          path: /
          method: get
