service: serverless-aws-terraform-intro

frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:*
      # TODO take ARN from SSM Store
      Resource: arn:aws:dynamodb:eu-central-1:705130529207:table/ChatMessages

functions:
  addChatMessage:
    handler: src/addChatMessage.handler
    events:
      - httpApi:
          path: /
          method: post
